### ISSUE TITLE
Kelvin versioning error

### ISSUE THREAD

**Issue by chaserene** [WETH10/WETH10#100]
this information would've probably been more useful to you earlier, but I've just heard about your project. so, WETH was created with Kelvin versioning.

https://github.com/dapphub/ds-weth/commit/becce32937cec782bef35f69eb6bcf3e74688c41

https://chat.makerdao.com/channel/oasis?msg=sy73LpH8EYLdXDBX2

if you're not sure what Kelvin versioning is, here's an explainer: https://jtobin.io/kelvin-versioning

while the augmentations you added are very interesting, this should be rather called WETH8. calling it WETH10 is ignoring the spirit in which WETH was created and what its developers stood for.

tough there may be a reason why your implementation is *not* WETH8, which I'll explain in the next issue.

**Comment by albertocuestacanada** [comment]
Someone did mention Kelvin versioning ages ago, I opened [the jtobin link that you mention](https://jtobin.io/kelvin-versioning), and sounded so outlandish that I decided he was a troll. Never heard about this again.

So we settled for WETH10, which sounded better than WETH-v2, the original choice.

**Comment by chaserene** [comment]
he wasn't trolling, it exists. much of [Urbit](https://urbit.org/blog/toward-a-frozen-operating-system/) uses Kelvin versioning. actually, up to a point [Maker itself](https://steemit.com/makerdao/@nikolai/maker-doesn-t-really-have-voting) was built in the same way. Maker was the first project that needed and engineered a wrapped ether token.

**Comment by albertocuestacanada** [comment]
Yeah, I get it. Unfortunately, it's deployed now as WETH10 :man_shrugging:
