### ISSUE TITLE
lack of canonicalness

### ISSUE THREAD

**Issue by chaserene** [WETH10/WETH10#101]
back when WETH9 was deployed, an ecosystem-wide standardization took place to make sure all major players agree on and integrate the same wrapped ether token. this is obviously a requirement for general acceptance and thus usefulness.

https://blog.0xproject.com/canonical-weth-a9aa7d0279dd

excuse me if it's just my ignorance, but so far I didn't come across such coordination for your wrapped token. if that's the case, I think it's erroneous to version it relative to WETH9, whether you call it WETH10 or WETH8 (#100). it implies a link that's not there. an appropriate name would be something else that is not related to these numbers.

**Comment by chaserene** [comment]
given this and the Kelvin versioning error, an unambiguously distinct versioning scheme would be more beneficial. e.g. WETH-plus|pro|xt|ultra|etc.

**Comment by albertocuestacanada** [comment]
As mentioned in a different issue, it's now deployed as WETH10, so there isn't much we can do.

And I feel offended about the comments on the lack of coordination. This wasn't some kind of secret project and it was widely publicised. Anyone that cared could have participated and many did.

All your comments are appreciated, but would have been appreciated a lot more if they would have been done in time. I personally would have been very grateful for someone to go around and convince all the major platforms we were serious. As it happened, we did this in our free time as well and as we could, and I'm sorry if it leaves you unsatisfied.
