### ISSUE TITLE
Transfers to the contract should withdraw

### ISSUE THREAD

**Issue by alcueca** [WETH10/WETH10#105]
A transfer to 0x0 becomes a withdraw, but it will be better UX if transfers to the contract do the same.

**Comment by cyanlink** [comment]
Someone already lost 195 WETH in the contract by transferring to the WETH9 contract address, see [My Reddit Post](https://www.reddit.com/r/CryptoCurrency/comments/sgdxtg/psa_we_should_do_something_for_todays_half/hv0c4wq/?context=3)
This lost would have been avoided if this implementation was deployed.

**Comment by alcueca** [comment]
👋
