### ISSUE TITLE
Implicit total supply invariant is broken with the current flash loan functionality

### ISSUE THREAD

**Issue by GNSPS** [WETH10/WETH10#51]
Bringing over a discussion from Twitter.

I think that the current way the flash mint function is built is dangerous because it breaks the invariant that total supply of a token should never exceed `2^256 -1` (or MAX_UINT256).

https://github.com/WETH10/WETH10/blob/main/contracts/WETH10.sol#L111-L125

Giving a specific example of how this invariant could be broken:

```
total supply == sum(account balances)

balance(account_1) == 100 Wei

**Account 2 uses Flash Mint**

balance(account_2) == 2^256 - 1 Wei

total supply == 2^256 + 99 Wei > 2^256 - 1 Wei
```

Even though this invariant is not very clearly specified in the ERC20 standard, I do believe it is widely accepted and implicitly used by many of Ethereum's developers.
And so, I firmly believe that, if the flash minting functionality is deployed to main net, it should also abide to this invariant.

**Comment by MrChico** [comment]
Not to mention all of the uses of unsafe addition (`balanceOf[to] += value`) that could be forced to overflow in the presence of unbounded minting

**Comment by wighawag** [comment]
It also prevent from being compliant with ERC20 since logically the sum of all balances should be equal to the result of `totalSupply()` and if the sum of all balances can reach higher than 2^256-1 then no implementation of totalSupply can ever be correct : https://github.com/WETH10/WETH10/issues/52

**Comment by Austin-Williams** [comment]
I agree with this. I'd recommend having `totalSupply` return the sum of all WETH in all account balances (including any flash-minted WETH) at any given time.

This would require deleting [L56](https://github.com/WETH10/WETH10/blob/main/contracts/WETH10.sol#L56), creating a `_totalSupply` state variable, increasing the `_totalSupply` when minting and flash-minting, and decreasing the `_totalSupply` when withdrawing or repaying flash-mints.

This will add to gas costs, but they are gas costs that all ERC20 tokens have to deal with.

It also makes the `totalSupply` function meaningful. As it stands now, there is little value in the output of the `totalSupply` function (as we can already access the ETH balance of WETH10 via ETH's native `address(_account).balance` function.

**Comment by albertocuestacanada** [comment]
Fixed in #63, I feel bad about the extra gas use of keeping `totalSupply` in check, more so when it was broken in WETH9 and no one was bothered in the last 3 years.

**Comment by albertocuestacanada** [comment]
Fixing `totalSupply` so that it doesn't count Ether received via self-destruct will cost the community about $5000 per day, or about $2M per year. (250000 transactions/day, 40 GWei, 5000 gas, $400 USD/ETH)

Given that no one has had an issue with this for such a long time, is it really worth it to keep track of the supply in a separate variable instead of using `address(this).balance`. @Austin-Williams? @GNSPS? @wighawag?

**Comment by Austin-Williams** [comment]
> is it really worth it to keep track of the supply in a separate variable instead of using `address(this).balance`

This is a design decision that depends largely on priorities, which will be different for different people.

I _personally_ tend to think correctness should be prioritized above efficiency, and I do think that the gas costs here are worth keeping WETH10 in line with the ERC20 standards/intentions.

That being said, if you are willing to sacrifice some correctness for efficiency, the `totalSupply` seems like the least-bad place to do it. Like you said, WETH9 has done this for years and it hasn't stopped anyone from using it. I don't think it would be a deal-killer for anyone.

**Comment by albertocuestacanada** [comment]
I think that's a sacrifice I'm willing to make. 5K per transaction is quite a lot in a contract like this.

**Comment by lepidotteri** [comment]
> I think that's a sacrifice I'm willing to make. 5K per transaction is quite a lot in a contract like this.

I agree
