### ISSUE TITLE
totalSupply is not ERC20 compliant

### ISSUE THREAD

**Issue by wighawag** [WETH10/WETH10#52]
Bring this from twitter : https://twitter.com/wighawag/status/1319658306697371649

As currently implemented, the function totalSupply is not compliant with the ERC20 standard if the following happen:
- ETH is sent to WETH10 through a self destruct
- during a flash loan

For totalSupply to be compliant, 
1. the sum of all Transfer (from zero address) minus the sum of all Transfer (to zero address) need to be equal to totalSupply
2. the sum of all balances should be equal to totalSupply()

flash loan as currently implemented breaks 2.
self destruct with ETH sent to WETH10 breaks 1.

**Comment by albertocuestacanada** [comment]
Fixed for flash loan (#63).

As for self-destruct, it is currently broken in WETH9 and fixing it would require an extra SSTORE with `deposit` and `withdraw`. Would that be worth it?
