### ISSUE TITLE
Decide on FlashMinterLike interface

### ISSUE THREAD

**Issue by moodysalem** [WETH10/WETH10#54]
https://github.com/WETH10/WETH10/blob/main/contracts/WETH10.sol#L12

This interface isn't necessary, because the msg sender already knows the amount they called flash mint with, so just call with the data

**Comment by shark0der** [comment]
Passing the amount as a parameter is cheaper than writing the amount to storage in the calling contract.

**Comment by moodysalem** [comment]
You don't need to write it to storage, it can be encoded in the data by the caller

**Comment by albertocuestacanada** [comment]
Fixed in #63, I think.

**Comment by albertocuestacanada** [comment]
As a comment on #63, from @moodysalem:
> you just native call the address with the input data. the input data can encode the function selector of the target contract in addition to all the arguments. it's not any less safe to do it this way. e.g. i may call directly into the uniswap weth/dai pair to sell the weth as the target of the flash mint, and then from the swap call back into my own contract, having already swapped weth for some other asset. this is gas cheaper than transferring weth to my own contract first (implementing flash minter like interface) and then selling on uniswap which involves multiple transfers of weth. uniswap may not be a good example given the use case is probably covered by flash swaps, but the point is the interface is not needed for safety

**Comment by albertocuestacanada** [comment]
Since we already discarded the idea of minting to arbitrary addresses, allowing calling arbitrary methods of `msg.sender` is not a huge improvement over calling `executeOnFlashMint` on `msg.sender`.

`executeOnFlashMint` can easily be coded to redirect to any contract method based on `calldata`, at the cost of an internal call. Most developers will also be more familiar calling regular functions than using native call with a function selector.

**Comment by moodysalem** [comment]
> Since we already discarded the idea of minting to arbitrary addresses, allowing calling arbitrary methods of `msg.sender` is not a huge improvement over calling `executeOnFlashMint` on `msg.sender`.
> 
> 
> 
> `executeOnFlashMint` can easily be coded to redirect to any contract method based on `calldata`, at the cost of an internal call. Most developers will also be more familiar calling regular functions than using native call with a function selector.

I don't feel strongly about it if you cannot mint to arbitrary address. Separately, always encoding the minted amount in the interface means they won't wastefully call balanceOf(address(this)) to get the amount minted when they could encode it in the data, so if you're keeping the interface you might also want to keep the amount parameter imo

**Comment by albertocuestacanada** [comment]
The `data` parameter will always likely include the `amount` minted and the relevant `user`.

Take into account that `flashMint` will never be executed by EOAs, so whichever contract calls `flashMint` probably needs to know which account initiated the transaction when inside the `executeOnFlashMint` callback.

We could pass `user`, `value` and `data` to `flashMint`, only for them to be passed on to `executeOnFlashMint`.
Or we could leave it as is now, with only `data` passed on to `executeOnFlashMint`, leaving the caller to encode `user`, `value` and whatever they are going to need into `data`.

In any case, calling `balanceOf(address(this))` is not needed, and gas costs will be very similar for all options. It's more a matter of usability and clarity than anything else.

**Comment by albertocuestacanada** [comment]
Using the same interface as MakerDAO (and possibly the same process) for flash minting would make integration easier.

https://github.com/hexonaut/dss-flash/blob/master/src/flash.sol
