### ISSUE TITLE
unnecessary address check in balanceOf

### ISSUE THREAD

**Issue by moodysalem** [WETH10/WETH10#57]
https://github.com/WETH10/WETH10/blob/5efe3d994447d6000b6cbdaca31872f6aa112ecb/contracts/WETH10.sol#L67

the ternary is not worth it when 99% of the time balanceOf isn't called on the contract, and you should just have an invariant test that checks the token balance of the contract is always 0

related is removing the function altogether and just renaming `_balanceOf` to `balanceOf`

**Comment by moodysalem** [comment]
i see this is happening because of this trick

https://github.com/WETH10/WETH10/blob/5efe3d994447d6000b6cbdaca31872f6aa112ecb/contracts/WETH10.sol#L56

this trick is jank, and the tradeoff is in the gas cost of balanceOf, just add a require with a nice message

**Comment by Austin-Williams** [comment]
+1. This trick is clever, but not worth:

1. The additional gas cost when calling `balanceOf`.
2. Breaking the common (and useful) assumption that `totalSupply` equals the sum of account balances.

More generally, I don't think preventing users from transferring WETH to the WETH contract is best done via the smart contract. I think it is better done via wallets. Adding foot-gun protection at the smart contract level is a recipe for increased contract complexity and gas costs. (Just my two cents.)

**Comment by albertocuestacanada** [comment]
Outdated as per [#63](https://github.com/WETH10/WETH10/pull/63).

I'll estimate the dollar cost of the footgun protection at current transaction levels, versus the amount of ETH locked in WETH9.
