### ISSUE TITLE
consider removing receive

### ISSUE THREAD

**Issue by moodysalem** [WETH10/WETH10#61]
https://github.com/WETH10/WETH10/blob/5efe3d994447d6000b6cbdaca31872f6aa112ecb/contracts/WETH10.sol#L70-L77

imo not really any more usable than deposit and not gas cheaper

**Comment by albertocuestacanada** [comment]
We were requested to keep it there for backwards compatibility with WETH9.

**Comment by moodysalem** [comment]
I don't really expect most contracts just point at the new WETH... Is it worth breaking backwards compatibility to improve the UX? Not clear to me one way or the other, but I see the argument for it (in-progress contracts can just point at the new WETH).

**Comment by albertocuestacanada** [comment]
I don't see how the UX would be improved by removing a function. You could argue that we would reduce the attack surface by removing it, but we are probably certain that it is safe to use.
