### ISSUE TITLE
Stopping WETH transfers to the WETH contract is not worth it.

### ISSUE THREAD

**Issue by albertocuestacanada** [WETH10/WETH10#64]
Assuming these numbers:
300000 daily transactions.
40 Gwei/GAS
400 USD/ETH

Each `require` to stop transfers to the WETH contract is ~30 gas. That's about $200 per day.

There are $21000 locked in the WETH contract after three years of operation. The `require` will waste that much in less than four months.

**Comment by dmihal** [comment]
Sorry, I've been away from this for a bit.

What happened to the balanceOf hack? That would do this without using any extra gas?

**Comment by albertocuestacanada** [comment]
We introduced limits to WETH minting, because otherwise we could end having more than uint256.max WETH and that would be wrong.

Since a flash mint can be combined with every other function, the minting limits were placed in `flashMint` and all `deposit` methods. That also ensures there can be no overflow.

If there can be no overflow, then we don't need to check for it, so we only left `require` to ensure that WETH is not transferred to the WETH contract. That allowed us to remove the `balanceOf` hack, which was not needed. That left us with simpler code. 

I think that it would be better not to prevent WETH transfers to the WETH contract, because it is uneconomical to do so, but I also know that it might be a controversial choice.

I want your opinion in particular, because I know this is something you feel strongly about.

**Comment by albertocuestacanada** [comment]
Found a satisfactory solution in #79.
