### ISSUE TITLE
Upgrade to Hardhat + Waffle

### ISSUE THREAD

**Issue by lepidotteri** [WETH10/WETH10#68]
including moving away all test suites from Truffle/OZ env

@albertocuestacanada what do you think Alberto, is this something that you wish for?

**Comment by albertocuestacanada** [comment]
I would love it if you could get this done.

**Comment by albertocuestacanada** [comment]
I added you as a collaborator to the repo so that you can open the PR directly here. Please be aware that as of #72 we are using buidler-deploy.
