### ISSUE TITLE
WETH9 in constructor prevent the use of create2 for deterministic address across chains

### ISSUE THREAD

**Issue by wighawag** [WETH10/WETH10#69]
Having weth9 in the constructor is unnecessary and prevent the use of create 2 for deterministic address across chains (see https://github.com/WETH10/WETH10/pull/22#issuecomment-715420941)  unless weth9 has itself the same address across chains (but believe it is not the case, hence : https://github.com/WETH10/WETH10/blob/2ec96e9895f86af2628badcc9b8f0b14fe136aa1/migrations/1_deploy.js#L4 )

Instead of having WETH10 tied to WETH9 the various `convert` functions could accept an extra argument specifying the WETH contract that should receive the eth.

This would also allow easy transition to a future WETH11 if any.

**Comment by albertocuestacanada** [comment]
Fixed via #71
