### ISSUE TITLE
Let's prevent sending to address(0)

### ISSUE THREAD

**Issue by k06a** [WETH10/WETH10#74]
It is not possible to distinguish `Transfer(wallet, 0, amount)` event happened because of the wrong transfer or withdrawal operation.

**Comment by albertocuestacanada** [comment]
In which scenario would that be a problem?

**Comment by k06a** [comment]
Events analysis will not allow to determine were tokens sent to 0 address or they were burnt

**Comment by albertocuestacanada** [comment]
You probably mean withdrawn.

Events analysis should check the user balance or the contract interacting with WETH10 to know what happened.

This contract doesn't follow the same rules as every other contract. Its functions are expected to be executed an insane number of times each day. Any change that increases the gas use even by a tiny amount should have a strong reason.

**Comment by albertocuestacanada** [comment]
Found a satisfactory solution in #79
