### ISSUE TITLE
The result of totalSupply() could mismatch the sum of all balances plus flashSupply

### ISSUE THREAD

**Issue by k06a** [WETH10/WETH10#75]
I feel really bad that we rely on actual contract `balance` here: https://github.com/WETH10/WETH10/blob/main/contracts/WETH10.sol#L56

```solidity
/// @dev Returns the total supply of WETH10 as the Ether held in this contract.
function totalSupply() external view override returns(uint256) {
  return address(this).balance + flashSupply;
}
```

We should understand that balance could be increased externally and would not match the sum of balances plus flashSupply:
- [Remember that Ether can be forcibly sent to an account](https://consensys.github.io/smart-contract-best-practices/recommendations/#remember-that-ether-can-be-forcibly-sent-to-an-account)
- [Forcibly Sending Ether to a Contract](https://consensys.github.io/smart-contract-best-practices/known_attacks/#forcibly-sending-ether-to-a-contract)

**Comment by albertocuestacanada** [comment]
This has been discussed before (#51).

This issue already exists in WETH9, and over 3 years it hasn't had any impact. Fixing it would have extra gas costs in all `deposit`, `withdraw` and `flashMint` functions.

Based on this, we are not fixing it in WETH10.
