### ISSUE TITLE
DOMAIN_SEPARATOR function is missing

### ISSUE THREAD

**Issue by dmihal** [WETH10/WETH10#89]
The ERC-2612 spec defines a public view function for retrieving the permit DOMAIN_SEPARATOR:

``` solidity
function DOMAIN_SEPARATOR() external view returns (bytes32)
```

This function is missing from WETH10.

Furthermore, the domain separator is currently calculated every time permit() is called. The function would be more gas efficient if the value was calculated once in the constructor and stored.

**Comment by Ro5s** [comment]
great flag @dmihal ~~ here's my stitch: https://github.com/WETH10/WETH10/pull/90

**Comment by wighawag** [comment]
I added a comment on the PR, but for to better discuss it I am replying here too :

hard-coding in the constructor a domain separator that depends on the chainId will cause issues when a splitting hard fork happens.
message signed for the original chainId will be replayable on both fork, and user of the the side that use a different chainId will have issues with wallets preventing them to use a different chainId.

in my opinion, the extra gas cost for on-demand domain separator computation is worth it.

**Comment by Ro5s** [comment]
closing this issue as resolved by https://github.com/WETH10/WETH10/pull/90

thanks for checking this issue out and sharing thoughts!
